### ISSUE TITLE
Isti problem kao ostali sva panela

### ISSUE THREAD

**Issue by rudarot** [BLIZZARD-STRESSER/O-Neon.info-Leaked#1]
Jel znas cega moze bit problem? Kad stavis box (machine) ne doda nista, kad stavis server primer na postojeci uradis samo edit i onda pokusas da dodas server sa mod onda daje "Greska server ne postoji" a user i pas su vec kreirani u linux.

Greška
Taj server ne postoji.

**Comment by R00tS3c** [comment]
php lib ssh2 je star na ovaj panel i ne podrzava noviji OS za game masine na debian 9 bi trebalo da radi, mozda i ne nzm
